// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStore.Models;

#nullable disable

namespace MusicStore.Migrations
{
    [DbContext(typeof(MusicStoreContext))]
    [Migration("20230807205751_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MusicStore.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"), 1L, 1);

                    b.Property<string>("GenreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            GenreId = "pop",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music116/v4/c0/54/97/c05497aa-c19f-bf4f-de29-71edf30fbefb/075679688767.jpg/170x170bb.png",
                            Price = 10.99,
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barbie The Album"
                        },
                        new
                        {
                            AlbumId = 2,
                            GenreId = "pop",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music126/v4/5e/3f/00/5e3f0031-5753-bd87-93e7-cdc9a479928b/075679690432.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "chemistry"
                        },
                        new
                        {
                            AlbumId = 3,
                            GenreId = "country",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music126/v4/3b/02/ea/3b02ea2d-2586-59d7-d2b8-e9b6af6b52b3/23UMGIM63932.rgb.jpg/170x170bb.png",
                            Price = 13.99,
                            ReleaseDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Speak Now (Taylor's Version)"
                        },
                        new
                        {
                            AlbumId = 4,
                            GenreId = "kpop",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music126/v4/50/e3/e0/50e3e0a3-d11c-d277-de39-a672a258ed4b/8809928950990_Cover.jpg/170x170bb.png",
                            Price = 5.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "KILL MY DOUBT - EP"
                        },
                        new
                        {
                            AlbumId = 5,
                            GenreId = "pop",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/49/3d/ab/493dab54-f920-9043-6181-80993b8116c9/19UMGIM53909.rgb.jpg/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lover"
                        },
                        new
                        {
                            AlbumId = 6,
                            GenreId = "alternative",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/6c/d6/97/6cd69741-63e0-d56b-3bf2-902606b43f1b/23SYMIM05048.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Maine"
                        },
                        new
                        {
                            AlbumId = 7,
                            GenreId = "videogame",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music126/v4/f8/6c/c8/f86cc8e6-69fa-b811-85f0-b72f90aa54f1/PA00120119_1_167817_jacket.jpg/170x170bb.png",
                            Price = 44.990000000000002,
                            ReleaseDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Xenoblade Chronicles 3 (Original Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 8,
                            GenreId = "rock",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/f0/c7/c8/f0c7c8f4-4319-d357-ddaf-566ef8e2194e/081227979379.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1976, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Their Greatest Hits 1971-1975"
                        },
                        new
                        {
                            AlbumId = 9,
                            GenreId = "alternative",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music122/v4/76/43/92/764392cc-de5e-eadd-8ccc-ba0e3ec04401/5054526647565.png/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1990, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "I Do Not Want What I Haven't Got"
                        },
                        new
                        {
                            AlbumId = 10,
                            GenreId = "country",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music113/v4/7d/24/14/7d241439-671a-d957-9613-2f738f43a064/196589485991.jpg/170x170bb.png",
                            Price = 13.99,
                            ReleaseDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gettin' Old"
                        },
                        new
                        {
                            AlbumId = 11,
                            GenreId = "country",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/c3/d0/1c/c3d01c88-73e7-187e-fd62-e1744de979a6/21UMGIM09915.rgb.jpg/170x170bb.png",
                            Price = 13.99,
                            ReleaseDate = new DateTime(2021, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fearless (Taylor's Version)"
                        },
                        new
                        {
                            AlbumId = 12,
                            GenreId = "pop",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/3e/c8/00/3ec80000-5f41-b9d4-0ccd-6350fa102fb1/5054526780682.png/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1987, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lion and the Cobra"
                        },
                        new
                        {
                            AlbumId = 13,
                            GenreId = "soundtrack",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music126/v4/2e/02/1d/2e021d5b-9ebe-91a6-7cc4-98c502203a59/23UMGIM44883.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy, Vol. 3: Awesome Mix, Vol. 3 (Original Motion Picture Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 14,
                            GenreId = "pop",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music125/v4/ba/16/42/ba1642a8-0c75-a83d-3b9c-8c2eba140dc5/00843930033133.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "reputation"
                        },
                        new
                        {
                            AlbumId = 15,
                            GenreId = "country",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music112/v4/2c/d4/d1/2cd4d14d-d89c-d7d5-8ae7-bbca55e23c4f/4050538875423.jpg/170x170bb.png",
                            Price = 10.99,
                            ReleaseDate = new DateTime(2022, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bell Bottom Country"
                        },
                        new
                        {
                            AlbumId = 16,
                            GenreId = "pop",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music116/v4/b7/0a/bc/b70abcc1-b835-99c5-ea32-6fee2155605a/075679675002.jpg/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barbie The Album (Best Weekend Ever Edition)"
                        },
                        new
                        {
                            AlbumId = 17,
                            GenreId = "singersongwriter",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music116/v4/b5/3b/9f/b53b9fa9-8ef9-72b3-f34b-289d93d62a00/603497832095.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Joni Mitchell at Newport (Live)"
                        },
                        new
                        {
                            AlbumId = 18,
                            GenreId = "soundtrack",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music126/v4/84/24/ce/8424cefe-738c-4c9d-fb18-6e86d36399fe/SQEX-11039-1_3000x3000.jpg/170x170bb.png",
                            Price = 35.990000000000002,
                            ReleaseDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "FINAL FANTASY XVI Original Soundtrack"
                        },
                        new
                        {
                            AlbumId = 19,
                            GenreId = "soundtrack",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/27/fa/ca/27faca2e-7f7a-cf17-ae3e-647294d52713/697.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oppenheimer (Original Motion Picture Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 20,
                            GenreId = "country",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music116/v4/98/5a/09/985a0908-223c-c3e3-8175-fa2abc241302/196871169363.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Memory Lane"
                        },
                        new
                        {
                            AlbumId = 21,
                            GenreId = "kpop",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music116/v4/d3/4b/7e/d34b7e1e-af3b-43b6-2949-7a8c652a1bc9/196922462726_Cover.jpg/170x170bb.png",
                            Price = 4.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NewJeans 2nd EP 'Get Up'"
                        },
                        new
                        {
                            AlbumId = 22,
                            GenreId = "videogame",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music116/v4/e7/43/b4/e743b4c6-10fb-f366-52b4-92094b879fd6/PA00120120_1_167816_jacket.jpg/170x170bb.png",
                            Price = 29.989999999999998,
                            ReleaseDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Xenoblade Chronicles: Definitive Edition (Original Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 23,
                            GenreId = "pop",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music126/v4/c2/4c/36/c24c3631-08b8-b576-345a-259b395f8dbd/5054197591464.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "- (Deluxe)"
                        },
                        new
                        {
                            AlbumId = 24,
                            GenreId = "country",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music126/v4/9f/3c/0a/9f3c0a60-f9e0-a34e-60e5-0be1f182896b/23UMGIM63932.rgb.jpg/170x170bb.png",
                            Price = 13.99,
                            ReleaseDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Speak Now (Taylor's Version)"
                        },
                        new
                        {
                            AlbumId = 25,
                            GenreId = "rock",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/cd/43/e7/cd43e76f-4ff1-f700-d84f-86eeea7fa5bb/828768588925.jpg/170x170bb.png",
                            Price = 10.99,
                            ReleaseDate = new DateTime(1988, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 26,
                            GenreId = "country",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/34/12/78/34127801-ad2b-4469-4916-d661bba34a94/20UMGIM71875.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2020, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Starting Over"
                        },
                        new
                        {
                            AlbumId = 27,
                            GenreId = "pop",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music116/v4/09/e3/d0/09e3d0f2-2dac-c8a6-c203-e53cab676343/196871273671.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "tori"
                        },
                        new
                        {
                            AlbumId = 28,
                            GenreId = "pop",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/60/10/80/601080b3-b9f6-2eaa-d74e-d4098d39fe7e/5054526649187.png/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(1997, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "So Far… The Best of Sinéad O'Connor"
                        },
                        new
                        {
                            AlbumId = 29,
                            GenreId = "rock",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music112/v4/2f/0a/fb/2f0afb49-2e70-3b52-95ce-29b3775ef1fe/196589493545.jpg/170x170bb.png",
                            Price = 7.9900000000000002,
                            ReleaseDate = new DateTime(2022, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NOW That's What I Call Classic Rock"
                        },
                        new
                        {
                            AlbumId = 30,
                            GenreId = "rock",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music116/v4/a1/47/ba/a147ba91-31cd-ef4d-d785-040036d14598/12CMGIM34362.rgb.jpg/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chronicle: The 20 Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 31,
                            GenreId = "pop",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music115/v4/09/01/16/090116af-770e-23da-21a9-6bd30782eda5/00843930013562.rgb.jpg/170x170bb.png",
                            Price = 10.99,
                            ReleaseDate = new DateTime(2014, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1989"
                        },
                        new
                        {
                            AlbumId = 32,
                            GenreId = "rock",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/34/ee/21/34ee21ae-e18d-6195-dc02-65d2344d23c9/23UMGIM36455.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Starcatcher"
                        },
                        new
                        {
                            AlbumId = 33,
                            GenreId = "soundtrack",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music114/v4/3b/46/fe/3b46fe36-3fc6-8aca-8953-71f504fd0222/14DMGIM05236.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy: Awesome Mix, Vol. 1 (Original Motion Picture Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 34,
                            GenreId = "alternative",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music126/v4/11/7a/b8/117ab805-6811-8929-18b9-0fad7baf0c25/17UMGIM98210.rgb.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(2017, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evolve"
                        },
                        new
                        {
                            AlbumId = 35,
                            GenreId = "rbsoul",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music126/v4/e9/a8/ec/e9a8ec80-24fd-4d8d-3823-ac87e5f71104/cover.jpg/170x170bb.png",
                            Price = 10.99,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Rebirth of Marvin"
                        },
                        new
                        {
                            AlbumId = 36,
                            GenreId = "rbsoul",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music116/v4/60/47/31/604731b0-89c3-2ddb-e4c5-98285e99ce4b/196282898050.png/170x170bb.png",
                            Price = 5.1600000000000001,
                            ReleaseDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "June 22 - EP"
                        },
                        new
                        {
                            AlbumId = 37,
                            GenreId = "hiphoprap",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music116/v4/5a/6d/1a/5a6d1a4e-ac13-c7e8-1eba-e80a35651622/23UMGIM07672.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "HOPE"
                        },
                        new
                        {
                            AlbumId = 38,
                            GenreId = "reggae",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music126/v4/f6/03/94/f6039435-7be4-ec98-e791-73104a7e593f/197773096986_cover.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Endless Summer"
                        },
                        new
                        {
                            AlbumId = 39,
                            GenreId = "kpop",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music126/v4/54/dd/b4/54ddb472-761d-3a04-bf74-ec81c5106d31/cover_KM0017975_1.jpg/170x170bb.png",
                            Price = 5.9900000000000002,
                            ReleaseDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "HOUSE OF TRICKY : HOW TO PLAY - EP"
                        },
                        new
                        {
                            AlbumId = 40,
                            GenreId = "country",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/e2/4b/60/e24b6016-8278-bb18-cf5d-d44bf68371da/00602547223838.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Traveller"
                        },
                        new
                        {
                            AlbumId = 41,
                            GenreId = "soundtrack",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/06/26/23/0626234a-12a7-7139-02d0-a3a70a406c49/859775800151_cover.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "RWBY, Vol. 9 (Music from the Rooster Teeth Series)"
                        },
                        new
                        {
                            AlbumId = 42,
                            GenreId = "electronic",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/c3/ee/ab/c3eeab38-a108-2eb2-b432-97db4cef4f6a/5056614706703.png/170x170bb.png",
                            Price = 3.96,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blackbox Life Recorder 21f / In a Room7 F760 - EP"
                        },
                        new
                        {
                            AlbumId = 43,
                            GenreId = "singersongwriter",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/2a/c1/cf/2ac1cf24-2a07-c62e-921c-357aba15d7f4/mzi.vosghqus.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(1988, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tracy Chapman"
                        },
                        new
                        {
                            AlbumId = 44,
                            GenreId = "country",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music116/v4/1d/a3/55/1da35509-ea85-d568-d29d-83e464f53ff9/093624856498.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Religiously. The Album."
                        },
                        new
                        {
                            AlbumId = 45,
                            GenreId = "kpop",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music116/v4/09/bc/96/09bc9676-b952-20d8-ea7d-cfa6bedbac77/cover_KM0017967_1.jpg/170x170bb.png",
                            Price = 5.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "13egin - EP"
                        },
                        new
                        {
                            AlbumId = 46,
                            GenreId = "rock",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music115/v4/d2/48/f4/d248f4ae-a7e4-a48e-1588-6617de3e8d76/mzi.izeorbmm.jpg/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(1988, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 47,
                            GenreId = "rock",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music112/v4/57/6f/c7/576fc76a-2eb4-11b1-a5dd-ad2aee4cdf0f/13UABIM04230.rgb.jpg/170x170bb.png",
                            Price = 7.9900000000000002,
                            ReleaseDate = new DateTime(2012, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 48,
                            GenreId = "country",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music112/v4/be/ea/e9/beeae98a-33a4-6e1d-6efc-b8dd098b0a2c/093624866459.jpg/170x170bb.png",
                            Price = 7.9900000000000002,
                            ReleaseDate = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Summertime Blues - EP"
                        },
                        new
                        {
                            AlbumId = 49,
                            GenreId = "rock",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music125/v4/88/90/0d/88900ddb-b23e-c1e6-8147-20eb92340076/081227397128.jpg/170x170bb.png",
                            Price = 27.989999999999998,
                            ReleaseDate = new DateTime(2003, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Very Best of Eagles"
                        },
                        new
                        {
                            AlbumId = 50,
                            GenreId = "pop",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/60/f8/a6/60f8a6bc-e875-238d-f2f8-f34a6034e6d2/14UMGIM07615.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1992, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ABBA Gold: Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 51,
                            GenreId = "metal",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music126/v4/f7/50/56/f75056b7-d390-d215-51c5-3695dc6fe468/810083961095.png/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "72 Seasons"
                        },
                        new
                        {
                            AlbumId = 52,
                            GenreId = "country",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music122/v4/25/7c/f2/257cf2e2-6c7a-3212-1b27-a684cf85a62c/196589083906.jpg/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Can I Take My Hounds to Heaven?"
                        },
                        new
                        {
                            AlbumId = 53,
                            GenreId = "rock",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music126/v4/8d/71/f1/8d71f1e2-4457-34c5-b214-a6d992b0777c/8720996002919.png/170x170bb.png",
                            Price = 11.99,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "First Last Time"
                        },
                        new
                        {
                            AlbumId = 54,
                            GenreId = "metal",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music116/v4/e2/c6/0f/e2c60f68-7cec-fa08-6dd3-891aa72c247e/5401148000849_cover.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Take Me Back To Eden"
                        },
                        new
                        {
                            AlbumId = 55,
                            GenreId = "musicals",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music115/v4/a6/63/54/a6635418-7d49-b237-d1c9-ba85fa57dbc6/075679886613.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2017, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Greatest Showman (Original Motion Picture Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 56,
                            GenreId = "metal",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/18/93/db/1893db5c-ddd1-b95c-3112-b9b83bcceab0/0093624986553.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1991, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Metallica"
                        },
                        new
                        {
                            AlbumId = 57,
                            GenreId = "rock",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music116/v4/f2/98/fb/f298fb48-1e0e-6ad4-4cff-fb824b77f02e/15UMGIM59587.rgb.jpg/170x170bb.png",
                            Price = 12.99,
                            ReleaseDate = new DateTime(2000, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1"
                        },
                        new
                        {
                            AlbumId = 58,
                            GenreId = "rock",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music112/v4/91/03/14/9103142e-9c42-3658-4d89-5f786ec5fdf1/196589142092.jpg/170x170bb.png",
                            Price = 7.9900000000000002,
                            ReleaseDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NOW That's What I Call '90s Alternative Rock"
                        },
                        new
                        {
                            AlbumId = 59,
                            GenreId = "pop",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/91/dc/dc/91dcdcc0-0844-5257-e89c-fceba19673bc/886449239580.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(2021, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NOW That's What I Call A Decade! The 80s"
                        },
                        new
                        {
                            AlbumId = 60,
                            GenreId = "pop",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music118/v4/4d/6f/51/4d6f518a-aed8-17fe-6727-ea26b2185ee4/888880473011.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(2008, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NOW That's What I Call the '80s"
                        },
                        new
                        {
                            AlbumId = 61,
                            GenreId = "soundtrack",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/cb/59/f4/cb59f4e3-69b5-f95c-cc5d-22637b29e139/00050087368777.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2017, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy, Vol. 2 (Original Motion Picture Soundtrack) [Awesome Mix, Vol. 2]"
                        },
                        new
                        {
                            AlbumId = 62,
                            GenreId = "hardrock",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music125/v4/79/98/f7/7998f761-20e0-aa8e-4fb2-190062af1638/603497894161.jpg/170x170bb.png",
                            Price = 6.9900000000000002,
                            ReleaseDate = new DateTime(1984, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            AlbumId = 63,
                            GenreId = "rock",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music126/v4/50/41/c9/5041c992-e078-77c1-442a-ff896abd59db/196871063197.jpg/170x170bb.png",
                            Price = 10.99,
                            ReleaseDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "But Here We Are"
                        },
                        new
                        {
                            AlbumId = 64,
                            GenreId = "soundtrack",
                            Image = "https://is2-ssl.mzstatic.com/image/thumb/Music126/v4/3a/2e/50/3a2e50ad-9e5b-8070-5b32-9684772b78c2/780163645224.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Miraculous: Ladybug & Cat Noir, The Movie (Original Motion Picture Soundtrack)"
                        },
                        new
                        {
                            AlbumId = 65,
                            GenreId = "rock",
                            Image = "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/af/7b/a2/af7ba295-c0c0-ba8d-17da-5cc52959a602/mzi.ykpmzuxm.jpg/170x170bb.png",
                            Price = 17.989999999999998,
                            ReleaseDate = new DateTime(2008, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "No End In Sight: The Very Best of Foreigner (Remastered)"
                        },
                        new
                        {
                            AlbumId = 66,
                            GenreId = "rock",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music114/v4/ad/d9/22/add9226e-9c33-246b-e528-a1a96d05df48/mzi.onpokbmx.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1975, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "America's Greatest Hits: History"
                        },
                        new
                        {
                            AlbumId = 67,
                            GenreId = "rock",
                            Image = "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/4d/08/2a/4d082a9e-7898-1aa1-a02f-339810058d9e/14DMGIM05632.rgb.jpg/170x170bb.png",
                            Price = 24.989999999999998,
                            ReleaseDate = new DateTime(2000, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greatest Hits I, II & III: The Platinum Collection"
                        },
                        new
                        {
                            AlbumId = 68,
                            GenreId = "rock",
                            Image = "https://is4-ssl.mzstatic.com/image/thumb/Music112/v4/78/61/dd/7861dd44-f796-08ea-c8ff-7f8a12a86db1/15UMGIM69649.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1993, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 69,
                            GenreId = "reggae",
                            Image = "https://is3-ssl.mzstatic.com/image/thumb/Music113/v4/ea/20/06/ea2006f9-7512-cf9c-7b44-78116156875e/12UMGIM14712.rgb.jpg/170x170bb.png",
                            Price = 9.9900000000000002,
                            ReleaseDate = new DateTime(1984, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Legend – The Best of Bob Marley & The Wailers (2002 Edition)"
                        });
                });

            modelBuilder.Entity("MusicStore.Models.AlbumArtist", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("AlbumArtists");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 2,
                            ArtistId = 2
                        },
                        new
                        {
                            AlbumId = 3,
                            ArtistId = 3
                        },
                        new
                        {
                            AlbumId = 4,
                            ArtistId = 4
                        },
                        new
                        {
                            AlbumId = 5,
                            ArtistId = 3
                        },
                        new
                        {
                            AlbumId = 6,
                            ArtistId = 5
                        },
                        new
                        {
                            AlbumId = 7,
                            ArtistId = 6
                        },
                        new
                        {
                            AlbumId = 8,
                            ArtistId = 7
                        },
                        new
                        {
                            AlbumId = 9,
                            ArtistId = 8
                        },
                        new
                        {
                            AlbumId = 10,
                            ArtistId = 9
                        },
                        new
                        {
                            AlbumId = 11,
                            ArtistId = 10
                        },
                        new
                        {
                            AlbumId = 12,
                            ArtistId = 8
                        },
                        new
                        {
                            AlbumId = 13,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 14,
                            ArtistId = 10
                        },
                        new
                        {
                            AlbumId = 15,
                            ArtistId = 11
                        },
                        new
                        {
                            AlbumId = 16,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 17,
                            ArtistId = 11
                        },
                        new
                        {
                            AlbumId = 18,
                            ArtistId = 12
                        },
                        new
                        {
                            AlbumId = 19,
                            ArtistId = 13
                        },
                        new
                        {
                            AlbumId = 20,
                            ArtistId = 14
                        },
                        new
                        {
                            AlbumId = 21,
                            ArtistId = 15
                        },
                        new
                        {
                            AlbumId = 22,
                            ArtistId = 7
                        },
                        new
                        {
                            AlbumId = 23,
                            ArtistId = 17
                        },
                        new
                        {
                            AlbumId = 24,
                            ArtistId = 3
                        },
                        new
                        {
                            AlbumId = 25,
                            ArtistId = 18
                        },
                        new
                        {
                            AlbumId = 26,
                            ArtistId = 19
                        },
                        new
                        {
                            AlbumId = 27,
                            ArtistId = 20
                        },
                        new
                        {
                            AlbumId = 28,
                            ArtistId = 8
                        },
                        new
                        {
                            AlbumId = 29,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 30,
                            ArtistId = 21
                        },
                        new
                        {
                            AlbumId = 31,
                            ArtistId = 3
                        },
                        new
                        {
                            AlbumId = 32,
                            ArtistId = 22
                        },
                        new
                        {
                            AlbumId = 33,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 34,
                            ArtistId = 23
                        },
                        new
                        {
                            AlbumId = 35,
                            ArtistId = 24
                        },
                        new
                        {
                            AlbumId = 36,
                            ArtistId = 25
                        },
                        new
                        {
                            AlbumId = 37,
                            ArtistId = 26
                        },
                        new
                        {
                            AlbumId = 38,
                            ArtistId = 27
                        },
                        new
                        {
                            AlbumId = 39,
                            ArtistId = 28
                        },
                        new
                        {
                            AlbumId = 40,
                            ArtistId = 19
                        },
                        new
                        {
                            AlbumId = 41,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 42,
                            ArtistId = 29
                        },
                        new
                        {
                            AlbumId = 43,
                            ArtistId = 30
                        },
                        new
                        {
                            AlbumId = 44,
                            ArtistId = 31
                        },
                        new
                        {
                            AlbumId = 45,
                            ArtistId = 32
                        },
                        new
                        {
                            AlbumId = 46,
                            ArtistId = 33
                        },
                        new
                        {
                            AlbumId = 47,
                            ArtistId = 34
                        },
                        new
                        {
                            AlbumId = 48,
                            ArtistId = 35
                        },
                        new
                        {
                            AlbumId = 49,
                            ArtistId = 7
                        },
                        new
                        {
                            AlbumId = 50,
                            ArtistId = 36
                        },
                        new
                        {
                            AlbumId = 51,
                            ArtistId = 37
                        },
                        new
                        {
                            AlbumId = 52,
                            ArtistId = 38
                        },
                        new
                        {
                            AlbumId = 53,
                            ArtistId = 39
                        },
                        new
                        {
                            AlbumId = 54,
                            ArtistId = 40
                        },
                        new
                        {
                            AlbumId = 55,
                            ArtistId = 41
                        },
                        new
                        {
                            AlbumId = 56,
                            ArtistId = 37
                        },
                        new
                        {
                            AlbumId = 57,
                            ArtistId = 42
                        },
                        new
                        {
                            AlbumId = 58,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 59,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 60,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 61,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 62,
                            ArtistId = 43
                        },
                        new
                        {
                            AlbumId = 63,
                            ArtistId = 44
                        },
                        new
                        {
                            AlbumId = 64,
                            ArtistId = 1
                        },
                        new
                        {
                            AlbumId = 65,
                            ArtistId = 49
                        },
                        new
                        {
                            AlbumId = 66,
                            ArtistId = 50
                        },
                        new
                        {
                            AlbumId = 67,
                            ArtistId = 51
                        },
                        new
                        {
                            AlbumId = 68,
                            ArtistId = 52
                        },
                        new
                        {
                            AlbumId = 69,
                            ArtistId = 53
                        });
                });

            modelBuilder.Entity("MusicStore.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            FullName = "Various Artists"
                        },
                        new
                        {
                            ArtistId = 2,
                            FullName = "Kelly Clarkson"
                        },
                        new
                        {
                            ArtistId = 3,
                            FullName = "Taylor Swift"
                        },
                        new
                        {
                            ArtistId = 4,
                            FullName = "ITZY"
                        },
                        new
                        {
                            ArtistId = 5,
                            FullName = "The Maine"
                        },
                        new
                        {
                            ArtistId = 6,
                            FullName = "Yasunori Mitsuda / ACE (TOMOri Kudo, CHiCO) / Kenji Hiramatsu / Manami Kiyota / Mariam Abounnasr / Yutaka Kunigo"
                        },
                        new
                        {
                            ArtistId = 7,
                            FullName = "Eagles"
                        },
                        new
                        {
                            ArtistId = 8,
                            FullName = "Sinéad O'Connor"
                        },
                        new
                        {
                            ArtistId = 9,
                            FullName = "Luke Combs"
                        },
                        new
                        {
                            ArtistId = 10,
                            FullName = "Lainey Wilson"
                        },
                        new
                        {
                            ArtistId = 11,
                            FullName = "Joni Mitchell"
                        },
                        new
                        {
                            ArtistId = 12,
                            FullName = "Masayoshi Soken"
                        },
                        new
                        {
                            ArtistId = 13,
                            FullName = "Ludwig Göransson"
                        },
                        new
                        {
                            ArtistId = 14,
                            FullName = "Old Dominion"
                        },
                        new
                        {
                            ArtistId = 15,
                            FullName = "NewJeans"
                        },
                        new
                        {
                            ArtistId = 16,
                            FullName = "Yoko Shimomura / ACE (TOMOri Kudo, CHiCO) / Kenji Hiramatsu / Manami Kiyota / Yasunori Mitsuda"
                        },
                        new
                        {
                            ArtistId = 17,
                            FullName = "Ed Sheeran"
                        },
                        new
                        {
                            ArtistId = 18,
                            FullName = "Journey"
                        },
                        new
                        {
                            ArtistId = 19,
                            FullName = "Chris Stapleton"
                        },
                        new
                        {
                            ArtistId = 20,
                            FullName = "Tori Kelly"
                        },
                        new
                        {
                            ArtistId = 21,
                            FullName = "Creedence Clearwater Revival"
                        },
                        new
                        {
                            ArtistId = 22,
                            FullName = "Greta Van Fleet"
                        },
                        new
                        {
                            ArtistId = 23,
                            FullName = "Imagine Dragons"
                        },
                        new
                        {
                            ArtistId = 24,
                            FullName = "October London"
                        },
                        new
                        {
                            ArtistId = 25,
                            FullName = "Rokosi"
                        },
                        new
                        {
                            ArtistId = 26,
                            FullName = "NF"
                        },
                        new
                        {
                            ArtistId = 27,
                            FullName = "The Elovaters"
                        },
                        new
                        {
                            ArtistId = 28,
                            FullName = "xikers"
                        },
                        new
                        {
                            ArtistId = 29,
                            FullName = "Aphex Twin"
                        },
                        new
                        {
                            ArtistId = 30,
                            FullName = "Tracy Chapman"
                        },
                        new
                        {
                            ArtistId = 31,
                            FullName = "Bailey Zimmerman"
                        },
                        new
                        {
                            ArtistId = 32,
                            FullName = "INFINITE"
                        },
                        new
                        {
                            ArtistId = 33,
                            FullName = "Fleetwood Mac"
                        },
                        new
                        {
                            ArtistId = 34,
                            FullName = "The Beach Boys"
                        },
                        new
                        {
                            ArtistId = 35,
                            FullName = "Zach Bryan"
                        },
                        new
                        {
                            ArtistId = 36,
                            FullName = "ABBA"
                        },
                        new
                        {
                            ArtistId = 37,
                            FullName = "Metallica"
                        },
                        new
                        {
                            ArtistId = 38,
                            FullName = "Tyler Childers"
                        },
                        new
                        {
                            ArtistId = 39,
                            FullName = "Ghost Hounds"
                        },
                        new
                        {
                            ArtistId = 40,
                            FullName = "Sleep Token"
                        },
                        new
                        {
                            ArtistId = 41,
                            FullName = "Benj Pasek & Justin Paul"
                        },
                        new
                        {
                            ArtistId = 42,
                            FullName = "Hugh Jackman"
                        },
                        new
                        {
                            ArtistId = 43,
                            FullName = "Keala Settle"
                        },
                        new
                        {
                            ArtistId = 44,
                            FullName = "Zac Efron"
                        },
                        new
                        {
                            ArtistId = 45,
                            FullName = "Zendaya"
                        },
                        new
                        {
                            ArtistId = 46,
                            FullName = "The Beatles"
                        },
                        new
                        {
                            ArtistId = 47,
                            FullName = "Van Halen"
                        },
                        new
                        {
                            ArtistId = 48,
                            FullName = "Foo Fighters"
                        },
                        new
                        {
                            ArtistId = 49,
                            FullName = "Foreigner"
                        },
                        new
                        {
                            ArtistId = 50,
                            FullName = "America"
                        },
                        new
                        {
                            ArtistId = 51,
                            FullName = "Queen"
                        },
                        new
                        {
                            ArtistId = 52,
                            FullName = "Tom Petty & The Heartbreakers"
                        },
                        new
                        {
                            ArtistId = 53,
                            FullName = "Bob Marley & The Wailers"
                        });
                });

            modelBuilder.Entity("MusicStore.Models.Genre", b =>
                {
                    b.Property<string>("GenreId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = "pop",
                            Name = "Pop"
                        },
                        new
                        {
                            GenreId = "country",
                            Name = "Country"
                        },
                        new
                        {
                            GenreId = "kpop",
                            Name = "K-Pop"
                        },
                        new
                        {
                            GenreId = "alternative",
                            Name = "Alternative"
                        },
                        new
                        {
                            GenreId = "videogame",
                            Name = "Video Game"
                        },
                        new
                        {
                            GenreId = "rock",
                            Name = "Rock"
                        },
                        new
                        {
                            GenreId = "soundtrack",
                            Name = "Soundtrack"
                        },
                        new
                        {
                            GenreId = "singersongwriter",
                            Name = "Singer/Songwriter"
                        },
                        new
                        {
                            GenreId = "rbsoul",
                            Name = "R&B/Soul"
                        },
                        new
                        {
                            GenreId = "hiphoprap",
                            Name = "Hip-Hop/Rap"
                        },
                        new
                        {
                            GenreId = "reggae",
                            Name = "Reggae"
                        },
                        new
                        {
                            GenreId = "electronic",
                            Name = "Electronic"
                        },
                        new
                        {
                            GenreId = "metal",
                            Name = "Metal"
                        },
                        new
                        {
                            GenreId = "musicals",
                            Name = "Musicals"
                        },
                        new
                        {
                            GenreId = "hardrock",
                            Name = "Hard Rock"
                        });
                });

            modelBuilder.Entity("MusicStore.Models.Album", b =>
                {
                    b.HasOne("MusicStore.Models.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusicStore.Models.AlbumArtist", b =>
                {
                    b.HasOne("MusicStore.Models.Album", "Album")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Models.Artist", "Artist")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStore.Models.Album", b =>
                {
                    b.Navigation("AlbumArtists");
                });

            modelBuilder.Entity("MusicStore.Models.Artist", b =>
                {
                    b.Navigation("AlbumArtists");
                });

            modelBuilder.Entity("MusicStore.Models.Genre", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
